name: Send-MSG-from-line-LAZYPAUL

on:
  schedule:
  # At 00:00 on Monday, Tuesday, Wednesday, Thursday, and Friday.
    - cron: "0 0 * * 1,2,3,4,5"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.9.0-beta.4'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run Python Code
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python Send_FX_to_Teresa.py
